Add TypeScript typings
jwplayer/jwplayer-react pull request #29
Opened 2024-03-25 08:15 UTC by amowu

### This PR will...

Add `@jwplayer/jwplayer-react` TypeScript types

### Why is this Pull Request needed?

Cannot find module '@jwplayer/jwplayer-react' or its corresponding type declarations.

![CleanShot 2024-03-25 at 16 10 20@2x](https://github.com/jwplayer/jwplayer-react/assets/559351/c7ac5212-2c74-4e72-af60-27290e0a8710)

### Are there any points in the code the reviewer needs to double check?

After `npm publish`, you can use tools like CodeSandbox to create a React TypeScript project to check whether `import JWPlayer from '@jwplayer/jwplayer-react'` will still display this error message.

### Are there any Pull Requests open in other repos which need to be merged with this?

N/A

#### Addresses Issue(s):

#4

2024-05-07 20:02 UTC, bosworthco approved these changes
Legend

2024-05-21 11:18 UTC, vyktoremario commented on types/jwplayer-react.d.ts
> +    const JWPlayerComponent: ComponentType<JWPlayerProps & HTMLProps<'video'>>;
Why not use `HTMLProps<HTMLVideoElement>` instead of `HTMLProps<'video'>>` ?
The latter will hardly pick all the relevant types for a video element

2024-05-21 11:19 UTC, vyktoremario requested changes
Left a comment

2024-05-28 05:50 UTC, bosworthco commented on types/jwplayer-react.d.ts
> +    const JWPlayerComponent: ComponentType<JWPlayerProps & HTMLProps<'video'>>;
@amowu could you please update? Would be awesome to make this available

2024-05-28 09:23 UTC, amowu commented on types/jwplayer-react.d.ts
> +    const JWPlayerComponent: ComponentType<JWPlayerProps & HTMLProps<'video'>>;
https://github.com/jwplayer/jwplayer-react/pull/29/commits/e3dc6a684c5674b04f6cff2cc12d9795e641abee

2024-05-28 09:51 UTC, bosworthco commented
Minor update needed to `type DidMountCallback = (DidMountCallbackArguments) => void;`

See #28

2024-06-22 02:52 UTC, amowu commented on types/jwplayer-react.d.ts
> +    const JWPlayerComponent: ComponentType<JWPlayerProps & HTMLProps<'video'>>;
@vyktoremario

2026-08-10 19:42 UTC, closed without merging